# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit flag-o-matic linux-info shell-completion

DESCRIPTION="Disposable, confined development environments for AI coding agents"
HOMEPAGE="https://github.com/h5i-dev/h5i"
SRC_URI="https://github.com/h5i-dev/${PN}/archive/refs/tags/v${PV}.tar.gz
	-> ${P}.gh.tar.gz"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64"

# web: the 'h5i ui' box console. Upstream's default, and the only reason this
# package would ever want a Node toolchain — crates/h5i-core/build.rs runs
# 'npm ci' + vite to produce web/dist, which rust-embed then bakes into the
# binary. USE=-web builds with --no-default-features: no axum, no embedder, no
# Node, and 'h5i ui' is simply absent.
# containers: the 'container' confinement tier, which is rootless Podman.
IUSE="+web containers"

# Cargo resolves and downloads the whole crate graph at build time, and with
# USE=web so does npm. Same approach as sci-ml/kokoros — no vendored CRATES
# list, so the sandbox has to allow network.
RESTRICT="network-sandbox test"

RDEPEND="
	dev-libs/openssl:=
	containers? ( app-containers/podman )
"
DEPEND="${RDEPEND}"
BDEPEND="
	|| ( >=dev-lang/rust-1.85 >=dev-lang/rust-bin-1.85 )
	virtual/pkgconfig
	web? ( net-libs/nodejs[npm] )
"

# Landlock is what the 'process' and 'supervised' tiers are built on, and h5i
# fails closed rather than silently downgrading — so a kernel without it turns
# those tiers into hard errors at runtime. Warn rather than die: the other
# tiers (workspace, container, microvm) do not need it, and this also has to
# merge cleanly inside an image chroot whose kernel is not the running one.
CONFIG_CHECK="~SECURITY_LANDLOCK ~SECCOMP_FILTER ~USER_NS ~NET_NS ~PID_NS"
ERROR_SECURITY_LANDLOCK="CONFIG_SECURITY_LANDLOCK is off — the 'process' and 'supervised' tiers will fail. Note it must ALSO be listed in CONFIG_LSM to be active."

src_configure() {
	# The 'cc' crate compiles ring's C and assembly with the ebuild's CFLAGS.
	# On an LTO profile those become GCC LTO IR, which rustc's linker (lld)
	# cannot read, so every symbol in them goes missing at link time:
	#   rust-lld: error: undefined symbol: ring_core_0_17_14__LIMBS_reduce_once
	# Nothing in Cargo.toml can prevent that — the flags arrive from the
	# environment, so they have to be filtered here.
	filter-lto

	# Upstream pins openssl with features = ["vendored"], which would build a
	# private copy of OpenSSL into the binary and freeze it there — no system
	# security updates, which is a poor trade for a tool whose whole job is
	# confinement. openssl-sys checks this variable before the vendored
	# feature, so the system library wins without patching Cargo.toml.
	export OPENSSL_NO_VENDOR=1

	# libgit2 stays vendored on purpose: git2 0.20 tracks a specific upstream
	# libgit2 and a system version mismatch is the single most common build
	# failure in Rust git tooling. It carries no network stack of its own here
	# — its TLS comes from the system OpenSSL selected above.
	:
}

src_compile() {
	local features=()
	use web || features+=( --no-default-features )

	cargo build --release --bin h5i "${features[@]}" || die "cargo build failed"
}

src_install() {
	dobin target/release/h5i

	# Pre-generated by upstream's scripts/gen_man.sh and committed, so this
	# does not depend on running the binary we just built.
	doman man/man1/h5i.1

	# Completions come from the binary itself (clap_complete). Native-only
	# package, so executing it here is safe.
	local shell
	for shell in bash zsh fish; do
		target/release/h5i completion "${shell}" > "${T}"/h5i.${shell} ||
			die "generating ${shell} completion failed"
	done
	newbashcomp "${T}"/h5i.bash h5i
	newzshcomp "${T}"/h5i.zsh _h5i
	newfishcomp "${T}"/h5i.fish h5i.fish

	# Upstream ships a Claude Code skill for driving h5i; it is documentation
	# as far as the package manager is concerned, but it is useless in
	# /usr/share/doc where nothing looks for it.
	insinto /usr/share/${PN}/skills
	doins -r skills/h5i/.

	dodoc README.md MANUAL.md ROADMAP.md SECURITY.md
}

pkg_postinst() {
	elog "Confinement tiers and what each one needs beyond this package:"
	elog ""
	elog "  workspace   nothing — a separate git worktree, no confinement"
	elog "  process     CONFIG_SECURITY_LANDLOCK=y AND 'landlock' present in"
	elog "              CONFIG_LSM (or lsm= on the kernel command line)."
	elog "              Compiled but unlisted means inert."
	elog "  supervised  the above, plus net-firewall/nftables for the egress"
	elog "              allowlist"
	elog "  container   USE=containers (rootless Podman)"
	elog "  microvm     /dev/kvm plus the microsandbox runtime, which is not"
	elog "              packaged here"
	elog ""
	elog "Check the running kernel with:  cat /sys/kernel/security/lsm"
	elog ""
	if ! use web; then
		elog "Built with USE=-web: the 'h5i ui' box console is not included."
		elog ""
	fi
	elog "A Claude Code skill for h5i is installed in"
	elog "  /usr/share/${PN}/skills/"
}
